import classNames from "classnames"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { cookies } from "next/headers"
import { PropsWithChildren } from "react"
import AuthProvider from "./common/providers/Auth.provider"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "NextJS 14 Boilerplate",
  description: "Generated by Bora Biricik",
}

export default function RootLayout({ children }: PropsWithChildren) {
  const cookieStorage = cookies()
  const token = cookieStorage.get("token")?.value
  return (
    <html lang="en">
      <body className={classNames(inter.className)}>
        <AuthProvider token={token}>
          <main>{children}</main>
        </AuthProvider>
      </body>
    </html>
  )
}
