import classNames from "classnames"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { PropsWithChildren } from "react"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "NextJS 14 Boilerplate",
  description: "Generated by Bora Biricik",
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={classNames(inter.className)}>{children}</body>
    </html>
  )
}
